### ISSUE TITLE
Fix the start of the arrow

### ISSUE THREAD

**Issue by Ntorresb** [osisoft/sample-pi_vision_extensibility-rotating_arrow-js#18]
set the start part of the arrow at a fixed point to be able to incorporate it into a wind rose

**Comment by cbardini** [comment]
Hi @Ntorresb, thank you for your suggestion! The formal process for suggesting new samples is to post them on our [feedback site](https://feedback.aveva.com/). There is a [specific section for developer resources](https://pisystem.feedback.aveva.com/?category=7135134109509567625) as well. I will close this issue for now.
